#!/bin/bash

# source function library
. /etc/rc.d/init.d/functions


tomcat_running_home_dir=/home/ec2-user/bin

start()
{
	/bin/bash $tomcat_running_home_dir/start_tomcat.sh	
}

stop()
{
	/bin/bash $tomcat_running_home_dir/stop_tomcat.sh
}

restart() {
	stop
	start
}

status()
{
	/bin/bash $tomcat_running_home_dir/status_tomcat.sh
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	status)
		status
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|status}"
		RETVAL=2
esac
exit $RETVAL
